#当前项目部署的端口
server:
  port: 8769

spring:
    redis:
      host: 192.168.226.130
      port: 6379
      password:
      jedis:
        pool:
          max-active: 8
          max-wait: 10000ms
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0ms